### Register user
POST http://localhost:4505/users/register
Content-Type: application/json

{
    "username":"onan",
    "email":"onan@gmail.com",
    "password":"pass"
}

### Login
POST http://localhost:4505/users/login
Content-Type: application/json

{
    "email":"onan@gmail.com",
    "password":"pass"
}








### Create Posts
POST http://localhost:4505/posts/new-post
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9uYW4iLCJlbWFpbCI6Im9uYW5AZ21haWwuY29tIiwidXNlcmlkIjoiNDA3ZGMzZjgtN2ExZi00ZjgxLWJhOWUtNmVkZGRjNmE0N2M5IiwiaWF0IjoxNjk0MzkzMTEwLCJleHAiOjE2OTQ0MDc1MTB9.JnghgaDJXcPLa0e9_WyoLhPzUqpE1qcQuu_8fRBL934

{    
    "userid": "407dc3f8-7a1f-4f81-ba9e-6edddc6a47c9",
    "postCaption": "Goodtimes last",
    "postImage": "nerea.png"
}


### Get All Posts
GET http://localhost:4505/posts/posts
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9uYW4iLCJlbWFpbCI6Im9uYW5AZ21haWwuY29tIiwidXNlcmlkIjoiNDA3ZGMzZjgtN2ExZi00ZjgxLWJhOWUtNmVkZGRjNmE0N2M5IiwiaWF0IjoxNjk0MzkzMTEwLCJleHAiOjE2OTQ0MDc1MTB9.JnghgaDJXcPLa0e9_WyoLhPzUqpE1qcQuu_8fRBL934


### Delete Post
DELETE  http://localhost:4505/posts/delete
Content-Type: application/json
token: eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtldmluIiwiZW1haWwiOiJrZXZpbjFAZ21haWwuY29tIiwidXNlcmlkIjoiM2E4NWI2NTYtZjVhYS00M2VmLWEyMzctZWE3OTFjZjA1YTJiIiwiaWF0IjoxNjk0MDg3ODU0LCJleHAiOjE2OTQxMDIyNTR9.7MU6gWNp90RMapegDlqVNlpMfp8u-ijK6Ari_QSJq14

{
    "userid": "407dc3f8-7a1f-4f81-ba9e-6edddc6a47c9",
    "postid": "762628e4-226e-4aac-84c7-8ef05e3dec25"
}



### Likes
POST http://localhost:4505/likes/checklikes
Content-Type: application/json

{
    "postid": "3592bfd2-e726-4ca4-bd23-bde677f975fe",
    "userid": "3a85b656-f5aa-43ef-a237-ea791cf05a2b"
}

### Unlike post
POST http://localhost:4505/likes/unlikepost
Content-Type: application/json

{
   "postid": "3592bfd2-e726-4ca4-bd23-bde677f975fe",
   "userid": "3a85b656-f5aa-43ef-a237-ea791cf05a2b"
}


### Comments
POST http://localhost:4505/comments/addcomment
Content-Type: application/json

{
   "postid":"8d1bf9e5-cc79-4e6e-a6a8-53af05aeeb80",
   "userid":"3a85b656-f5aa-43ef-a237-ea791cf05a2b",
   "commentText": "wastage of our time"
}

### GetCommentsByPostID
GET http://localhost:4505/comments/getcommentsbyid/8d1bf9e5-cc79-4e6e-a6a8-53af05aeeb80
Content-Type: application/json

# to be fixed *********************************
### edit comments 
PUT http://localhost:4505/comments/editcomment/2ccf1694-c119-4071-8072-ba31a13dff43

{
    "commentText": "This is the edited comment"
}



### following 
POST http://localhost:4505/users/follow
Content-Type: application/json

{
    "followerUserId": "8e72a6c2-65cc-4d14-baaf-cba9f242e1b9",
    "followingUserId": "407dc3f8-7a1f-4f81-ba9e-6edddc6a47c9"
}



### unfollow
POST http://localhost:4505/users/unfollow
Content-Type: application/json

{
    "followerUserId": "3985457b-df76-4e10-94dc-671691669231",
    "followingUserId": "407dc3f8-7a1f-4f81-ba9e-6edddc6a47c9"
}

### count followers
GET http://localhost:4505/users/countfollow/407dc3f8-7a1f-4f81-ba9e-6edddc6a47c9

