### Register user
POST http://localhost:4505/users/register
Content-Type: application/json

{
    "username":"kevin",
    "email":"kevin1@gmail.com",
    "password":"pass"
}

### Login
POST http://localhost:4505/users/login
Content-Type: application/json

{
    "email":"kevin1@gmail.com",
    "password":"pass"
}








### Create Posts
POST http://localhost:4505/posts/new-post
Content-Type: application/json

{    
    "userid": "3a85b656-f5aa-43ef-a237-ea791cf05a2b",
    "postCaption": "Loyal Dog.",
    "postImage": "dog.jpg"
}


### Get All Posts
GET http://localhost:4505/posts/posts
Content-Type: application/json
token: eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtldmluIiwiZW1haWwiOiJrZXZpbjFAZ21haWwuY29tIiwidXNlcmlkIjoiM2E4NWI2NTYtZjVhYS00M2VmLWEyMzctZWE3OTFjZjA1YTJiIiwiaWF0IjoxNjk0MDg3ODU0LCJleHAiOjE2OTQxMDIyNTR9.7MU6gWNp90RMapegDlqVNlpMfp8u-ijK6Ari_QSJq14

### Likes
POST http://localhost:4505/likes/checklikes
Content-Type: application/json

{
    "userid": "3a85b656-f5aa-43ef-a237-ea791cf05a2b",
    "postid": "06143c86-dd9e-4f48-bcad-23168fe607f4"
}

### Unlike post
POST http://localhost:4505/likes/unlikepost
Content-Type: application/json

{
    "userid": "3a85b656-f5aa-43ef-a237-ea791cf05a2b",
    "postid": "06143c86-dd9e-4f48-bcad-23168fe607f4"
}